name: Build Android E2E APK (Auto)

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
      GENERAL_DEFAULT_BALANCE_HEX: '0x5f5e0ff' # 99999999 en hex

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: yarn setup:github-ci --no-build-ios

      - name: Generate automatic key
        id: generate-key
        run: |
          RANDOM_KEY=$(openssl rand -hex 32)
          echo "auto_key=$RANDOM_KEY" >> "$GITHUB_OUTPUT"

      - name: Build APK
        run: |
          yarn build:android:main:e2e
        env:
          AUTO_KEY: ${{ steps.generate-key.outputs.auto_key }}
          GENERAL_DEFAULT_BALANCE_HEX: ${{ env.GENERAL_DEFAULT_BALANCE_HEX }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: main-e2e-release.apk
          path: android/app/build/outputs/apk/prod/release/app-prod-release.apk
          retention-days: 7
